### ISSUE TITLE
there are an issue for Example 4.27

### ISSUE THREAD

**Issue by seenyea** [nickpoison/tsda#2]
there are an issue for Example 4.27 in this page. 
Here are url: 
https://github.com/nickpoison/tsda/blob/main/Rcode.md#chapter-4

```
 for (t in 2:num){ 
    w[t] = x[t]   - para[j]*w[t-1]
 }
```
if t is equal to 2, it mean w[2] = x[2] - w[1], as w[1] now is equal to 0. 
As the (4.23), w[1] is mean w[0], so you need change x[2] to x[1], so that we can get real w seires.

I have modified it, please check it.
```
for (t in 2:num){ 
    w[t] = x[t - 1]   - para[j]*w[t-1]
 }
```

**Comment by nickpoison** [comment]
it won't make any difference in the estimates, but instead of 
`c(0) -> w`  
use
`c(x[1])-> w`
and leave the rest as is
